baseURL = 'https://oevplus.ninfaj.ch/'
languageCode = 'de'
title = 'Ã–V Plus'

theme = 'oevplus-ch'
canonifyurls  = true
DefaultContentLanguage = "de"

[languages]
  [languages.de]
    languageName = "DE"
    weight = 1

  [languages.fr]
    languageName = "FR"
    weight = 2

[markup.goldmark.renderer]
  unsafe = true


